### ISSUE TITLE
nbclient execution doesn't do so in the notebook's directory

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#180]
In https://github.com/executablebooks/jupyter-book/issues/605 @bmcfee mentioned that notebooks that have relative dependencies in the code weren't working. I think that's be cause when we execute with `nbclient` (e.g. if execute == `auto`) then we don't execute the notebook in the directory where it exists: https://github.com/executablebooks/MyST-NB/blob/bb4f754c328f7d0e3fa6b6a18a93eaa0f5befacf/myst_nb/cache.py#L147

I think this can be fixed by specifying a `cwd=` argument to `execute(` (https://github.com/jupyter/nbclient/blob/2d862a9ab6f34c6c93761283aaa42d8f39dcf8e2/nbclient/client.py#L858) that points to the folder where the notebook lives

**Comment by chrisjsewell** [comment]
Yes we can add this, although I would note that ideally we should be allowing for some way to identify relative file dependencies (a.k.a assets), so that the notebook and its dependencies can be isolated during execution, e.g. moving them to a temporary directory, or even running them in a Docker container, etc. The former is how `jupter-cache`'s basic executor is implemented: https://github.com/executablebooks/jupyter-cache/blob/7bf1d6bce4a911622973252549748d326951039c/jupyter_cache/executors/basic.py#L157

**Comment by choldgraf** [comment]
yeah that makes sense - I think we should treat this as a short-term bug to fix (since it clashes with a user's expectations and how jupyter-cache works), and isolated execution more of a medium-term enhancement
