### ISSUE TITLE
Relationship With Notebook Cell Tags and Classic Notebook Extensions

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/MyST-NB#229]
In many of my classic UI notebooks, I make use of notebook extensions such as [Collapsible Headings](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/collapsible_headings/readme.html), and increasingly use cell tags to annotate cells that I want other custom extensions to process (eg [tab based styling](https://github.com/innovationOUtside/nb_extension_tagstyler)).

I can see how it might be possible to convert a `collapsible` tagged cell to a collapsible MyST invocation, and presumably extension filters could also generate MyST eg in accord with the Collapsible headings extension/settings, which I imagine use metadata flags to identify collapsible cells and their collapse state.

But I wonder whether there is any common ground or best practice for:

- using tags;
- writing extensions;
- writing extension filters;

that can be used to generate MyST documents that invoke styling similar to the styles I can apply via extensions?

Typically, I already edit Markdown in a classic notebook UI under Jupytext. One workflow I could imagine would take Jupytext markdown and then convert it via a series of filters to MyST. The filters would eg parse tags/metadata and then rewrite the MyST markdown to a suitable form.

**Comment by chrisjsewell** [comment]
This is related to #227 and something I'm going to look at soonish

**Comment by choldgraf** [comment]
I think that we should accept a commonly-used set of tags that trigger specific behavior, and recommend that for others who wish to move the behavior of extensions etc into the Jupyter Book world. Right now we have no "official" process by which new tags are added or supported but I think it'd be good to be transparent about this.

I think allowing for behavior from arbitrary extensions will be more difficult since there's so many ways that extensions can alter notebook behavior, and we also have to think about behavior across all of the different notebook UIs, many of which extensions don't cross boundaries. It's why I'd rather settle on a set of standard metadata pieces that we look for rather than considering any one single extension in this. Does that make sense?

**Comment by psychemedia** [comment]
@choldgraf Re:

> I'd rather settle on a set of standard metadata pieces that we look for rather than considering any one single extension in this

Yes, that absolutely makes sense. (Also, my apols for not doing a proper search of issues before raising a question.)
