### ISSUE TITLE
Markdown headers generated from code are not numbered with other headers

### ISSUE THREAD

**Issue by fdion** [executablebooks/MyST-NB#309]
Using jupyter notebooks (saving to md:myst with jupytext) for some chapters of a book (_with multiple parts, each with chapters and sections_), and instructions are pretty clear, except for one part I can't figure out: numbered headers from a loop.

For example, assuming a list of strings named items, I've tried:

```python
#%% md

# All Items

#%%
for item in items:
    display(Markdown(f"## Item {item}"))
    # some other stuff
```

The various sub headers do not show up, while the other stuff like figures and tables show up. So I tried:

```python
#%% md

# All Items

#%%

for item in items:
    display(HTML(f"\n<H2>Item {item}</H2>\n"))
    # some other stuff
```

The headers show up for each item, along with the other stuff, header is the right font size, but do not get numbered (_presumably because HTML is ignored when the book is built_) or included in the navigation / toc.

I've searched the documentation and couldn't find anything like that.

**Comment by fdion** [comment]
Ended up generating myst markdown files directly from python code / loop. Downside is I have to add them to the toc and ignore them to not push them to github. Then on github run the script to generate the markdown files and then build the book.

Not ideal, but this buys me some time until there is a better solution

**Comment by krassowski** [comment]
> The various sub headers do not show up

I identified a cause for this here: https://github.com/executablebooks/MyST-NB/issues/315#issuecomment-825981309

As for making the headers consistently numbered, the markdown from cell outputs may need to get stitched into the source markdown document on the tokens levels indeed, rather than - as currently - pasted in later on in the rendering step (see my comments in https://github.com/executablebooks/MyST-NB/pull/316).

**Comment by chrisjsewell** [comment]
heya, thanks for the feedback 🙏, I'm folding this issue in to #317
