### ISSUE TITLE
RFE: please provide `myst-parser` 0.19.x and `sphinx` 6.x support

### ISSUE THREAD

**Issue by kloczek** [executablebooks/MyST-NB#476]
https://github.com/executablebooks/MyST-NB/blob/385c4a7afb3a377486c1aa7a86b4c8a0e93484f5/pyproject.toml#L42-L45

https://github.com/executablebooks/MyST-Parser/releases/tag/v0.19.0

**Comment by kloczek** [comment]
Gentle ping .. any progress? 🤔

**Comment by tupui** [comment]
Sphinx 7 is out. It would be great to remove the pin.

**Comment by kloczek** [comment]
I'm not 100% but looks like sphinx 7 support already has been committed.
If that is true is it anything else which is on the outstanding list before next release 🤔

**Comment by aaaandi** [comment]
Since March 7 2023, MyST-Parser 1.0.0 is out, which changes nothing in the code compared to 0.19.2, but it could be more reasonable to update to 1.0.0 for clarity.

Since June 13, even MyST-Parser 2.0.0 is out that consists mainly of dependency upgrades.

Would be really cool if the dependency on MyST-Parser could be updated soon so that the nice new features introduced with 0.19.0 such as [attrs_inline](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#inline-attributes) and [attrs_block](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#block-attributes) extensions could be used.

**Comment by kloczek** [comment]
Sorry for asking .. how far is to next version which may be working with sphinx 7.x and latest myst-parser? 🤔

**Comment by kloczek** [comment]
Closing as 1.0.0 has been released.
